version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - FRONTEND_URL=http://localhost:3000
      - CERTIFICATES_DIR=/app/backend/assets/certificates
      - FONTS_DIR=/app/backend/assets/fonts
    volumes:
      - certificates:/app/backend/assets/certificates
      - fonts:/app/backend/assets/fonts
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  certificates:
  fonts: 