[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = []

[start]
cmd = "node --dns-result-order=ipv4first src/index.js"

[variables]
NODE_OPTIONS = "--dns-result-order=ipv4first"