# Cloudflare Pages configuration
name = "bill-gen-saas"
compatibility_date = "2023-12-01"

[site]
bucket = "./frontend/dist"
pages_build_output_dir = "frontend/dist"

[env.production]
routes = [
  { pattern = "/*", script = "" }
]

# Reroute all requests to /index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "scooter-bills-db"
database_id = "3aa1af6c-747f-4c27-8928-95f870009bfc" 