name = "scooter-bill-api"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "scooter-bills-db"
database_id = "3aa1af6c-747f-4c27-8928-95f870009bfc" 